name = "discord_club_app"
type = "webpack"
account_id = "42459c568b12d0902eeac887235b0c41"
workers_dev = false
route = "new.discord.club/*"
zone_id = "395adc5acb390afadb8494deeff28691"

[site]
bucket = "./dist"
entry-point = "workers-site"
